name: PoC Traducción Eqolibrium

on:
  push:
    branches:
      - main
    paths:
      - '**.html' # Solo se activa si tocas el HTML

jobs:
  translate_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install beautifulsoup4 deep-translator

      - name: Ejecutar script de traducción
        run: python traducir.py

      - name: Enviar al repositorio en Inglés
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DESTINATION_REPO_TOKEN }}
        with:
          source-directory: 'output' # Solo enviamos la carpeta con lo traducido y las imágenes
          destination-github-username: 'TU_USUARIO_DE_GITHUB' 
          destination-repository-name: 'eqolibrium-en'
          user-email: bot-traductor@poc.com
          commit-message: "Traducción automática de prueba"
          target-branch: main
